---
title: "Non Computational Neuroscience"
format:
  revealjs:
    code-fold: true
---

## Quantum Computing 101

# Intro

## Bloch Sphere
```{python}
from math import pi
from qiskit_textbook.widgets import plot_bloch_vector_spherical
coords = [pi/2,0,1] # [Theta, Phi, Radius]
plot_bloch_vector_spherical(coords) # Bloch Vector with spherical coordinates
```

## Bloch Sphere

```{python}
from math import pi
from qiskit_textbook.widgets import bloch_calc
bloch_calc()
```

## Quantum Circuits
"Circuit model": sequence of building blocks that carry out elementary computations called *gates*

```{mermaid}
flowchart LR
  A[input] --> B[algorithm]
  B --> C[output]
  style A fill:#ffffff,stroke-width:0px
  style C fill:#ffffff,stroke-width:0px
```

# Single qubit gates

- Classical example: The NOT gate
```{mermaid}
flowchart LR
  A["0 <br> 1"] --> B[NOT]
  B --> C["1 <br> 0"]
  style A fill:#ffffff,stroke-width:0px
  style C fill:#ffffff,stroke-width:0px
```
- Quantum example:
quantum gates are represented by unitary matrices: $$ \mathcal{U}^{\dagger} \mathcal{U}=\mathcal{1}$$

# Pauli Matrices:
- bit flit
```{mermaid}
flowchart LR
  A["|0> <br> |1>"] --> B["#963;x"]
  B --> C["|1> <br> |0>"]
  style A fill:#ffffff,stroke-width:0px
  style C fill:#ffffff,stroke-width:0px
```

\begin{equation*}
\sigma_X =
	\begin{pmatrix}
	0 & 1 \\
	1 & 0  \\
	\end{pmatrix}
\end{equation*}

- phase flip: rotation around z-axis by \[ \pi \]
```{mermaid}
flowchart LR
  A["|0> <br> |1>"] --> B["#963;z"]
  B --> C["|+> <br> |->"]
  style A fill:#ffffff,stroke-width:0px
  style C fill:#ffffff,stroke-width:0px
```

\begin{equation*}
\sigma_Z =
	\begin{pmatrix}
	0 & 1 \\
	1 & 0  \\
	\end{pmatrix}

\end{equation*}

- bit and phase flip
```{mermaid}
```{mermaid}
flowchart LR
  A["|0> <br> |1>"] --> B["#963;y"]
  B --> C["|i> <br> |-i>"]
  style A fill:#ffffff,stroke-width:0px
  style C fill:#ffffff,stroke-width:0px
``````

\begin{equation*}
\sigma_Y =
	\begin{pmatrix}
	1 & 0 \\
	0 & -1  \\
	\end{pmatrix}
\end{equation*}

-Hadamar gate: creates superpositions
```{mermaid}
flowchart LR
  A["|0> <br> |1>"] --> B[H]
  B --> C["|+> <br> |->"]
  style A fill:#ffffff,stroke-width:0px
  style C fill:#ffffff,stroke-width:0px
```

## Two qubit gates

```{mermaid}
flowchart LR
A[x <br> y] --> B[XOR]
B --> C["x #10753; y"]
```


- Classical example

<!-- style A fill:#ffffff,stroke-width:0px -->
<!--  style C fill:#ffffff,stroke-width:0px -->

- Quantum example: CNOT <=> reversible XOR

```{python}
from qiskit import QuantumCircuit
qc = QuantumCircuit(2)
qc.cx(0,1)
qc.draw('mpl')
```

## Entanglement

If a pure state $$ \ket{\psi_{AB}} $$ on systems A, B cannot be written as , it is entangled
